### ISSUE TITLE
Zalomení dlouhého textu v políčku

### ISSUE THREAD

**Issue by jakubboucek** [ridercz/Prohlaseni#2]
Při vložení dlouhého textu nedojde k zalomení řádku.
![](https://cdn.jakub-boucek.cz/screenshot/210301-szhyy.png)

Při tisku by se asi nativní `<input>` měl změnit na stylovaný  `<div>`, aby se přizpůsobil objemu zadaného textu.

**Comment by ridercz** [comment]
Nevím jak to vyřešit čistě pomocí tiskového stylu. Změnil jsem typ tohoto pole (kde to v jediném případě realisticky hrozí) na textarea a zvětšil ho, což by problém mělo vyřešit.
